language: ruby
script: "bundle exec jekyll build"
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/fe5446eae50768f32dbf
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false