lsi: false
markdown:  redcarpet
permalink: pretty
timezone: America/Los_Angeles
plugins:
  - jekyll-redirect-from
  - jemoji
exclude: [
  "README.md",
  "node_modules",
  "Gemfile*",
  "Gruntfile.js",
  "package.json",
  "vendor",
]
