lsi: false
markdown:  redcarpet
permalink: pretty
highlighter:  true
timezone: America/Los_Angeles
gems:
  - jekyll-redirect-from
  - jemoji
exclude: [
  "README.md",
  "bower.json",
  "bower_components",
  "node_modules",
  "Gemfile*",
  "Gruntfile.js",
  "package.json",
  "vendor",
]
